BinanceEndpoints = {
    "main1": "https://fapi.binance.com",
    "pub_ws": "wss://fstream.binance.com",
    "priv_ws": "wss://fstream.binance.com",
    "ping": ("/fapi/v1/ping", "GET"),
    "exchangeInfo": ("/fapi/v1/exchangeInfo", "GET"),
    "instrumentInfo": ("/fapi/v1/exchangeInfo", "GET"),
    "orderbook": ("/fapi/v1/depth", "GET"),
    "trades": ("/fapi/v1/trades", "GET"),
    "ohlcv": ("/fapi/v1/klines", "GET"),
    "markPrice": ("/fapi/v1/premiumIndex", "GET"),
    "allOpenOrders": ("/fapi/v1/openOrders", "GET"),
    "accountInfo": ("/fapi/v2/account", "GET"),
    "positionInfo": ("/fapi/v2/positionRisk", "GET"),
    "feeRate": ("/fapi/v1/commissionRate", "GET"),
    "listenKey": ("/fapi/v1/listenKey", "POST"),
    "pingListenKey": ("/fapi/v1/listenKey", "PUT"),
    "createOrder": ("/fapi/v1/order", "POST"),
    "amendOrder": ("/fapi/v1/order", "PUT"),
    "cancelOrder": ("/fapi/v1/order", "DELETE"),
    "cancelAllOrders": ("/fapi/v1/allOpenOrders", "DELETE"),
    "setLeverage": ("/fapi/v1/leverage", "POST"),
}
